version: '1'
services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: indonesia
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: 'root'
      UPLOAD_LIMIT: 10M